version: "3.0"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - database
    stdin_open: true
    tty: true